# Generated by Django 4.1.3 on 2022-11-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField(max_length=50)),
                ('descricion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuerza',
            fields=[
                ('id_fuerza', models.AutoField(primary_key=True, serialize=False)),
                ('fuerzapublica', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id_fuerza', models.AutoField(primary_key=True, serialize=False)),
                ('fuerzapublica', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tiposangre',
            fields=[
                ('id_rh', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rh', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personalfp',
            fields=[
                ('idpersonalfp', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(default=0)),
                ('nombres', models.TextField(max_length=100)),
                ('apellidos', models.TextField(max_length=100)),
                ('correoelectronico', models.TextField(max_length=60)),
                ('id_fuerza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaciudadanoApp.fuerza')),
                ('id_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaciudadanoApp.rango')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadanos',
            fields=[
                ('idciudadano', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombres', models.TextField(max_length=100)),
                ('apellidos', models.TextField(max_length=100)),
                ('fechadenacimiento', models.DateField()),
                ('lugardenacimiento', models.TextField(max_length=50)),
                ('fechadeexpedicion', models.DateField()),
                ('lugardeexpedicion', models.TextField(max_length=50)),
                ('estatura', models.IntegerField()),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultaciudadanoApp.estado')),
                ('id_rh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultaciudadanoApp.tiposangre')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
